/**
 * ecosystem.config.js — PM2 process configuration
 * =================================================
 * Run with:
 *   pm2 start ecosystem.config.js --env production
 *   pm2 reload ecosystem.config.js --env production  (zero-downtime reload)
 */

module.exports = {
  apps: [
    {
      name: 'alazab-api',
      script: 'index.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env_production: { NODE_ENV: 'production', PORT: 3004 },
      env_development: { NODE_ENV: 'development', PORT: 3004 },
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      log_file: './logs/api-combined.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      exp_backoff_restart_delay: 100,
      kill_timeout: 10000,
      listen_timeout: 10000,
      shutdown_with_message: true,
      wait_ready: false,
      pmx: true,
    },
    {
      name: 'alazab-mcp',
      script: './mcp/server.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env_production: { NODE_ENV: 'production', MCP_PORT: 4005 },
      env_development: { NODE_ENV: 'development', MCP_PORT: 4005 },
      error_file: './logs/mcp-error.log',
      out_file: './logs/mcp-out.log',
      log_file: './logs/mcp-combined.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      kill_timeout: 5000,
    },
    {
      name: 'alazab-openai-mcp',
      script: './mcp/openai/server.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env_production: {
        NODE_ENV: 'production',
        OPENAI_MCP_HOST: '127.0.0.1',
        OPENAI_MCP_PORT: 4015,
        OPENAI_MCP_PUBLIC_ORIGIN: 'https://api.alazab.com',
        OPENAI_MCP_RESOURCE: 'https://api.alazab.com',
        OPENAI_MCP_INTERNAL_GATEWAY_URL: 'http://127.0.0.1:4005/call',
        OPENAI_MCP_AUTH_MODE: 'supabase',
      },
      env_development: {
        NODE_ENV: 'development',
        OPENAI_MCP_HOST: '127.0.0.1',
        OPENAI_MCP_PORT: 4015,
        OPENAI_MCP_PUBLIC_ORIGIN: 'https://api.alazab.com',
        OPENAI_MCP_RESOURCE: 'https://api.alazab.com',
        OPENAI_MCP_INTERNAL_GATEWAY_URL: 'http://127.0.0.1:4005/call',
        OPENAI_MCP_AUTH_MODE: 'none',
      },
      error_file: './logs/openai-mcp-error.log',
      out_file: './logs/openai-mcp-out.log',
      log_file: './logs/openai-mcp-combined.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      kill_timeout: 5000,
    },
    {
      name: 'alazab-daftra-mcp',
      script: './mcp/daftra/server.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env_production: {
        NODE_ENV: 'production',
        MCP_DAFTRA_HOST: '127.0.0.1',
        MCP_DAFTRA_PORT: 4007,
        DAFTRA_OPENAPI_EXPECT_OPERATIONS: 301,
        DAFTRA_OPENAPI_STRICT_HASH: 'true',
      },
      env_development: {
        NODE_ENV: 'development',
        MCP_DAFTRA_HOST: '127.0.0.1',
        MCP_DAFTRA_PORT: 4007,
        DAFTRA_OPENAPI_EXPECT_OPERATIONS: 301,
        DAFTRA_OPENAPI_STRICT_HASH: 'false',
      },
      error_file: './logs/daftra-mcp-error.log',
      out_file: './logs/daftra-mcp-out.log',
      log_file: './logs/daftra-mcp-combined.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      exp_backoff_restart_delay: 100,
      kill_timeout: 5000,
    },
    {
      name: 'alazab-central-webhook',
      script: './central-webhook/server.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env_production: {
        NODE_ENV: 'production',
        CENTRAL_WEBHOOK_HOST: '127.0.0.1',
        CENTRAL_WEBHOOK_PORT: 4010,
      },
      env_development: {
        NODE_ENV: 'development',
        CENTRAL_WEBHOOK_HOST: '127.0.0.1',
        CENTRAL_WEBHOOK_PORT: 4010,
      },
      error_file: './logs/central-webhook-error.log',
      out_file: './logs/central-webhook-out.log',
      log_file: './logs/central-webhook-combined.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
      exp_backoff_restart_delay: 100,
      kill_timeout: 5000,
    },
  ],
};
