INSERT INTO public.projects (name, title_en, slug, client_name, category, status, location, description, content_ar, content_en, model_3d_embeds, stats, is_published, sort_order, year)
VALUES
('أبو عوف - بنها','Abu Auf - Banha','abu-auf-banha','Abu Auf','فرع تجاري','مكتمل','بنها، القليوبية',
 'مسح ثلاثي الأبعاد لفرع أبو عوف ببنها — ارتفاع سقف 3.40م، جدران داخلية 0.10م وخارجية 0.15م.',
 E'## أبو عوف بنها\n\n**الأبعاد:** ارتفاع السقف 3.40 م — سُمك الجدار الداخلي 0.10 م — سُمك الجدار الخارجي 0.15 م.\n\n**الإحصائيات:** المساحة بدون جدران 76.9 م² — مساحة الأرضية 46.3 م — الحجم 192 م³ — عدد الغرف 1 — الأبواب 4 — النوافذ 0.',
 E'## Abu Auf Banha\n\n**Dimensions:** Ceiling 3.40 m — Interior 0.10 m — Exterior 0.15 m.\n\n**Stats:** Surface 76.9 m² — Floor 46.3 m — Volume 192 m³ — Rooms 1 — Doors 4 — Windows 0.',
 '[{"provider":"magicplan","url":"https://3d.magicplan.app/#embed/?key=Y2M4MjY0ZWM4ZGQ0OGU4MzI4NjhhZDI1OWEyNjk1NDE5ZDU4NTk5MjVhMDA2NTljNDc1NTUzMGQ4MjNjZTMwMxPgr%2BAeXhBzlZ7j4k1EstSMTgd%2BQAnjaQcoq3n0tstBI8Hgu%2BagyEOCICZ42XlHIKL22SlYevbWMHWvj0yow2HQmi8NDwa%2Fnmui0bpt010b","title":"Abu Auf Banha 3D"}]'::jsonb,
 '{"ceiling_height_m":3.40,"interior_wall_m":0.10,"exterior_wall_m":0.15,"surface_no_walls_sqm":76.9,"floor_area_m":46.3,"volume_m3":192,"rooms":1,"doors":4,"windows":0}'::jsonb,
 true, 1, 2024),
('أبو عوف - أركان بلازا','Abu Auf - Arkan Plaza','abu-auf-arkan-plaza','Abu Auf','فرع تجاري','مكتمل','أركان بلازا، الشيخ زايد',
 'مسح ثلاثي الأبعاد لفرع أبو عوف بأركان بلازا — 12 غرفة و12 باباً و7 نوافذ.',
 E'## أبو عوف أركان بلازا\n\n**الأبعاد:** ارتفاع السقف 2.50 م — جدار داخلي 0.12 م — جدار خارجي 0.25 م.\n\n**الإحصائيات:** المساحة 183 م² — الأرضية 114 م — الحجم 516 م³ — الغرف 12 — الأبواب 12 — النوافذ 7.',
 E'## Abu Auf Arkan Plaza\n\nSurface 183 m² — Floor 114 m — Volume 516 m³ — Rooms 12 — Doors 12 — Windows 7.',
 '[{"provider":"magicplan","url":"https://3d.magicplan.app/#embed/?key=OTBiNTEzNjMzYTIyNWE0YTM1ZGZiZDMwZjRkOGQ1NDdmNDc3ZDhlMDQ0NzY2OGEwMTE5NGY1NGRmZTUxMTYyMWV8DT%2BlvMX1HW%2B65c5%2FPiv6Vn7EdSqdvS6h95mGfLdcfDK30Ylbs8maJwpyvuxjZLXln537hAEXG3YGxjvtRE4IWooddLyj5Rd6WjiYCucy","title":"Abu Auf Arkan Plaza 3D"}]'::jsonb,
 '{"ceiling_height_m":2.50,"interior_wall_m":0.12,"exterior_wall_m":0.25,"surface_no_walls_sqm":183,"floor_area_m":114,"volume_m3":516,"rooms":12,"doors":12,"windows":7}'::jsonb,
 true, 2, 2024),
('أبو عوف - فرع 3','Abu Auf - Branch 3','abu-auf-branch-3','Abu Auf','فرع تجاري','مكتمل','مصر',
 'مسح ثلاثي الأبعاد لفرع أبو عوف — 6 غرف و6 أبواب و6 نوافذ.',
 E'## أبو عوف — فرع 3\n\n**الأبعاد:** السقف 2.44 م — داخلي 0.12 م — خارجي 0.25 م.\n\n**الإحصائيات:** 92.1 م² — الأرضية 83.0 م — الحجم 274 م³ — 6 غرف — 6 أبواب — 6 نوافذ.',
 E'## Abu Auf — Branch 3\n\nSurface 92.1 m² — Floor 83.0 m — Volume 274 m³ — Rooms 6 — Doors 6 — Windows 6.',
 '[{"provider":"magicplan","url":"https://3d.magicplan.app/#embed/?key=MGNjM2MwZGRjMDIxODdhMTMwZWMyZTIwNjhjZTBhNDJkNDc1MzJjODE4OTQxM2Y2ZTk5Mzk4OTI1OGQ0NDQzNhLqDjboFyJcjRzvgta4Ki93h6dxwdKtVTEJKPoGXCgRbiujSFBlozOIwAj3rj5DT8M%2Fz0nXbZ8Rr4x4xA4q3J0cqBglPkQJWKhJDZk8z9Rj","title":"Abu Auf Branch 3 3D"}]'::jsonb,
 '{"ceiling_height_m":2.44,"interior_wall_m":0.12,"exterior_wall_m":0.25,"surface_no_walls_sqm":92.1,"floor_area_m":83.0,"volume_m3":274,"rooms":6,"doors":6,"windows":6}'::jsonb,
 true, 3, 2024),
('أبو عوف - فرع 4','Abu Auf - Branch 4','abu-auf-branch-4','Abu Auf','فرع تجاري','مكتمل','مصر',
 'مسح ثلاثي الأبعاد لفرع أبو عوف — غرفتان وبابان.',
 E'## أبو عوف — فرع 4\n\n**الأبعاد:** السقف 2.44 م — داخلي 0.12 م — خارجي 0.25 م.\n\n**الإحصائيات:** 52.8 م² — الأرضية 39.5 م — الحجم 195 م³ — غرفتان — بابان — 0 نوافذ.',
 E'## Abu Auf — Branch 4\n\nSurface 52.8 m² — Floor 39.5 m — Volume 195 m³ — Rooms 2 — Doors 2 — Windows 0.',
 '[{"provider":"magicplan","url":"https://3d.magicplan.app/#embed/?key=YWViZDAxMzE4ODc4M2I4MzVlZmE1YTQ1YmRiZDQwYmUxZTNmYjQ5OWUwYTYwYjMxMWY5YjVlNTRhZDNiMTU1Y1bOh1jIn1asxuqQvO3mAoB%2BQ6sjI12jBGPyKYJPvh%2F7AVBiwxrKEedkTOjTkAAPmnpkeY8oYqFz%2BKFNbPgxEcOQ%2FRiQKZUC0KmPGWZ5RkU8","title":"Abu Auf Branch 4 3D"}]'::jsonb,
 '{"ceiling_height_m":2.44,"interior_wall_m":0.12,"exterior_wall_m":0.25,"surface_no_walls_sqm":52.8,"floor_area_m":39.5,"volume_m3":195,"rooms":2,"doors":2,"windows":0}'::jsonb,
 true, 4, 2024),
('أبو عوف - اللوران','Abu Auf - El Loran','abu-auf-el-loran','Abu Auf','فرع تجاري','مكتمل','اللوران، الإسكندرية',
 'مسح ثلاثي الأبعاد لفرع أبو عوف باللوران — ارتفاع سقف 3.70م.',
 E'## أبو عوف اللوران\n\n**الأبعاد:** السقف 3.70 م — داخلي 0.10 م — خارجي 0.15 م.\n\n**الإحصائيات:** 49.1 م² — الأرضية 40.9 م — الحجم 177 م³ — غرفتان — بابان.',
 E'## Abu Auf El Loran\n\nSurface 49.1 m² — Floor 40.9 m — Volume 177 m³ — Rooms 2 — Doors 2 — Windows 0.',
 '[{"provider":"magicplan","url":"https://3d.magicplan.app/#embed/?key=ZGU0YjY4MzczOTk3OWVjNGJjMWNlODViOGFmNWU4NzBkOWJkODM4NTQ5ODA0ZTQ0NmYyYzliNzM2YzBhYjYyZFhszvHnRcw%2FZZxLuH744UTToZiy2%2BEPrd%2Fxswny3VkBz6RomXXPH%2B8BV61crDdw5w%3D%3D","title":"Abu Auf El Loran 3D"}]'::jsonb,
 '{"ceiling_height_m":3.70,"interior_wall_m":0.10,"exterior_wall_m":0.15,"surface_no_walls_sqm":49.1,"floor_area_m":40.9,"volume_m3":177,"rooms":2,"doors":2,"windows":0}'::jsonb,
 true, 5, 2024),
('أبو عوف - المنصورة المشاية','Abu Auf - Mansoura Mashaya','abu-auf-mansoura-mashaya','Abu Auf','فرع تجاري','مكتمل','المنصورة، الدقهلية',
 'مسح ثلاثي الأبعاد لفرع أبو عوف بمشاية المنصورة.',
 E'## أبو عوف المنصورة المشاية\n\n**الأبعاد:** السقف 3.60 م — داخلي 0.12 م — خارجي 0.25 م.\n\n**الإحصائيات:** 60.1 م² — الأرضية 41.2 م — الحجم 205 م³ — غرفتان — بابان.',
 E'## Abu Auf Mansoura Mashaya\n\nSurface 60.1 m² — Floor 41.2 m — Volume 205 m³ — Rooms 2 — Doors 2 — Windows 0.',
 '[{"provider":"magicplan","url":"https://3d.magicplan.app/#embed/?key=OThjY2VjZjVhMDJiMWJjZjUwMDk1OTRlYmY3MmI5OGE5NmY2MDMyNDhiMDM0MDMxYTQwNzllMjQzMDJlMWIwZFcHIQj6JXi1MqT5h6RYI%2Bw8CIBkSfHEDsK5z7Fuq2sfxYi5wklhp4ZRZrpg%2BEOEeC%2Foj1L9mC%2FPis2x5LsNzRL107giHOtKGnBsahI9wBzC","title":"Abu Auf Mansoura 3D"}]'::jsonb,
 '{"ceiling_height_m":3.60,"interior_wall_m":0.12,"exterior_wall_m":0.25,"surface_no_walls_sqm":60.1,"floor_area_m":41.2,"volume_m3":205,"rooms":2,"doors":2,"windows":0}'::jsonb,
 true, 6, 2024);